name: Tests cypress

on:
  push:
    baranches: [main]
  pull_request:
    baranches: [main]

jobs:
  build_and_cypress:
    runs-on: ubuntu-latest


    steps:
    #1. etape
      - name: Checkout repository
        uses: actions/checkout@v3

    #2. etape
      - name: preapre node.js
        uses: actions/setup-node@v3

    #3 etape
      - name: installer packages
        run: npm install

      #4 etape
      - name: Lancement du serveur
        run: |
          node server.js &
          SERVER_PID=$!

          npm wait-on http://localhost:3001

          npm run cypress:run

          kill $SERVER_PID




      

      
