name: Dire simplement Bonjour

on:
  push:
    baranches: [main]
  pull_request:
    baranches: [main]

jobs:
  dire_bonjour:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Dire Bonjour
      run: echo "Bonjour Blandine, Manon et Abdallah"